language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PL4IL5oUmnw4/FLY1ULWw6mvggdT7fcUC0BJSZMqTSXLxx5QXfJ5ViV1oj2L9NwhG1EsMh1BkNzhCYyTsLLIoOVDMzhk66alwKwpxjWJK6t60nhuhEJDbqdPqA1clVDU41kiSc4kMjHkCbsNdAW1AZKXYzTiHNx9CG5AazRnGdUGjk/1jPZSSkY9sD3uhu93k9hYtKzZnpfOweOpeVj34oIsuUK9dS6rUMoFy8qKPY/FnLkF7p9vXxt6com9jQyboI3hhWzRu7XtlzNElZJgusVJ4jMuRsJO8QAe3ycgPY7IW0mBoTQJsBzqLZPZnuBtMhXX0UPel0T57J+TNy5faEYFWwgaD4eASFwYgnoi/r2A9WYU/PCuQHOKQ+1+V0dz4jzK/HVajIBLeig9MBS2Ti9SD5V7Unn4GWdDxvWQY3hdqzRnI2gT7UZCHOn0gYfivakLmuK6TtDlv1sKXlPMfp4HXYIZo1+1SDKoDdoLeARv1pQU43yVbyCD2owZR92AgFm2lvdzC60ibwy2HxjJw8vbGaC8o3nT7AOHFYSb3/4fXYeqq6DWXVL9xYSipAjgSg2D3wfOpZeUuM6isQH3rhQhS9iYurj32MctsalScmu/j4Wz0YCrydmonz4acaqmQYIC41RKCBzj1X4py3jS3bXmHATakFvROJOvq7Husg4=
  app: photo-life-api
  on:
    repo: sgarcia30/photo-life-api
